package com.dfire.testBase;

import java.io.IOException;
import java.util.Iterator;
import java.util.Map;

import javax.annotation.Resource;

import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.testng.AbstractTestNGSpringContextTests;
import org.testng.annotations.DataProvider;

import com.alibaba.druid.pool.DruidDataSource;
import com.dfire.test.util.CsvDataProvider;
import com.twodfire.util.PropertiesUtil;

/* Generated by OneKey */

@ContextConfiguration(locations = { "classpath:applicationContext.xml" })
public class TestBase extends AbstractTestNGSpringContextTests {

	@Resource(name = "dataSource")
	public DruidDataSource druidDataSource;

	public static String csvFile;

	@DataProvider(name = "CsvDataProvider")		
	public Iterator<Object[]> data() throws Exception {
		return new CsvDataProvider(getCsvPath());
	}

	static {
		// 读取config.properties
		Map<String, String> propertiesMap = null;
		try {
			propertiesMap = PropertiesUtil.readProperties("config.properties");
		} catch (IOException e) {
			e.printStackTrace();
		}
		csvFile = propertiesMap.get("csvFile");
	}

	public String getCsvPath() {
		String folderName = this.getClass().getPackage().getName().replaceAll("com.dfire.test.", "");
		return csvFile + folderName + "/" + this.getClass().getSimpleName() + ".csv";
	}
}